export const onboardingCopy = {
  en: {
    welcomeEyebrow: 'YOU’RE IN',
    welcomeTitle: 'Welcome to Jentera!',
    welcomeSetup: 'Thanks for joining us early. Let’s give your AI Staff its first useful job and build something great together.',
    welcomeAccess: 'You’re signed in. Thanks for joining us early! Access is invitation-only for now; joining the waitlist does not start a subscription.',
    groupTitle: 'Thank you for supporting Jentera early.',
    groupIntro: 'You’re helping us build something awesome. We’d love to work together and listen to your feedback. Join our Founder WhatsApp Group for direct access to the founder—share ideas, report an issue, or get help with your first workflow. Joining is optional.',
    groupPrivacy: 'Other members may see your WhatsApp profile and the information you share. Don’t post passwords, private customer data or confidential files.',
    groupJoin: 'Join the Founder WhatsApp Group',
    workflowTitle: 'What would you like your AI Staff to help with first?',
    workflowIntro: 'Start with one piece of repetitive work. We’ll build your business context next, then prepare a first job you can review.',
    workflowCategories: { sales: 'Sales & follow-up', admin: 'Admin & data entry', reports: 'Reports', research: 'Research & monitoring', marketing: 'Marketing', other: 'Something else' },
    workflowExamples: { sales: 'Prepare quotations or follow-up drafts', admin: 'Update a spreadsheet or prepare documents', reports: 'Turn weekly figures into a useful report', research: 'Compare suppliers or monitor public information', marketing: 'Prepare a content plan or campaign drafts', other: 'Describe the work you want help with' },
    repeatedTask: 'What is one task you repeat every day or every week?',
    repeatedPlaceholder: 'Every Friday, I turn my sales spreadsheet into a weekly report…',
    workflowNext: 'Use this as my first workflow',
    workflowMissing: 'Choose a category and describe one repetitive task first.',
    workflowPrivacy: 'Don’t include passwords or private customer details. Choosing a workflow does not run or schedule it.',
    changeWorkflow: 'Change my first workflow',
    workflowCategoryField: 'First workflow category', workflowTaskField: 'Your repetitive task',
    workflowChoice: 'Your chosen workflow', workflowOutcome: 'A first deliverable and a repeatable plan to review',
    workflowPrompt: 'Help me prepare my first repeatable workflow for this task:',
    workflowInstructions: 'Prepare an editable first deliverable where possible, a repeatable checklist, the inputs needed, and which steps require my approval or a supported connection. Do not claim that this workflow is active or scheduled.',
    computerMoment: 'Meet your AI Staff.',
    readyChecks: ['Computer ready', 'Browser ready', 'Workspace ready', 'Jentera ready'],
    readyChecksNote: 'Setup verified on your target release. An idle computer may need to wake when you start a job.',
    learning: 'Building your business picture', readyToReview: 'Your business is taking shape.',
    selectedDetails: 'details selected', previewNote: 'Based on the details selected below. Nothing is confirmed yet.',
    sourceWaiting: 'Waiting', sourceReading: 'Reading', sourceRead: 'Read', sourceFailed: 'Could not read',
    draftReady: 'Your first draft is here.', responseReady: 'Here’s Jentera’s response.', contentOutcome: '3 editable posts and a one-week plan',
    replyOutcome: 'A reusable reply you can personalise', checklistOutcome: 'A step-by-step checklist for your work',
    workshopOutcome: 'A follow-up message ready for your review',
    steps: ['Introduce your business', 'Review what I found', 'Your first useful job'],
    title: 'Where can I learn about your business?',
    intro: 'Give me a page, a document, or a few sentences. I’ll turn it into business details you can check.',
    website: 'Website or public page', social: 'Another public page (optional)', upload: 'Upload a document', describe: 'Describe your business',
    limit: 'Reads the page you provide, not the whole website. For login-only or JavaScript-heavy pages, upload a document or describe your business.',
    fileNote: 'PDF, Word, images, text, Markdown or CSV. Up to 8 MB (text files: 1 MB). Only extracted facts are kept.',
    name: 'Business name', about: 'What do you offer, and who do you help?',
    fields: { 'business.name': 'Business name', 'business.about': 'About your business', 'business.address': 'Address', 'business.phone': 'Phone', 'business.email': 'Email' } as Record<string, string>,
    read: 'Learn about my business', reading: 'Reading your source…', review: 'Here’s what I understood.',
    reviewNote: 'These are proposed details, not verified claims. Edit what’s wrong and select only what you want Jentera to use.',
    source: 'Source', manual: 'You', empty: 'I couldn’t find enough clear business details. Try another page, upload a document, or describe the business. Nothing has been confirmed.',
    failed: 'That source could not be read. Try another source or add the details yourself.',
    back: 'Change source', confirm: 'Confirm details & prepare Jentera', saving: 'Saving your details…',
    consent: 'Confirming saves your selected details and starts preparing your business computer. You’ll choose a job next; nothing is sent or published.',
    retry: 'Try again', keep: 'Use this detail', missing: 'Add a source, document, or business description first.',
    resume: 'Your earlier inputs are here. Read the source now to build your real business knowledge.',
    jobs: 'Give your AI Staff its first job.',
    jobsNote: 'Choose a starting point, edit the brief, and ask Jentera to produce a draft. Nothing is sent or published.',
    draft: 'Your brief', start: 'Create this draft', starting: 'Starting your job…', open: 'View your work',
    waiting: 'Prepare and save your first job while your computer gets ready. Nothing runs until you choose to start it.',
    saveBrief: 'Save my first job', savingBrief: 'Saving your first job…', savedButton: 'First job saved',
    savedWaiting: 'Your brief is saved. You can leave this page and come back when your computer is ready.',
    savedReady: 'Your brief is saved and your computer is ready. Choose “Create this draft” to start.',
    saveFailed: 'Could not save your first job. Please try again.',
    content: 'A week of content', reply: 'An enquiry reply', checklist: 'A practical checklist',
    workshop: 'A workshop follow-up',
    safety: 'Use my confirmed business details. Do not invent prices, customers, results or policies. Mark missing information clearly. Create an editable Markdown document. Draft only: do not send, publish, schedule or contact anyone.',
    contentPrompt: 'Create a practical one-week content plan for my business, with three draft posts, intended audiences and clear calls to action.',
    replyPrompt: 'Draft a reusable first reply for a prospective customer asking about our services, with placeholders for details that depend on their enquiry.',
    checklistPrompt: 'Create a practical checklist for delivering our main service or product, from the initial enquiry to follow-up.',
    workshopPrompt: 'Draft a follow-up message for workshop participants, with placeholders for the workshop name, resources and feedback link.',
  },
  bm: {
    welcomeEyebrow: 'ANDA SUDAH MASUK',
    welcomeTitle: 'Selamat datang ke Jentera!',
    welcomeSetup: 'Terima kasih kerana menyertai kami dari awal. Mari beri Staf AI anda tugas pertama dan bina produk yang hebat bersama.',
    welcomeAccess: 'Anda sudah log masuk. Terima kasih kerana menyertai kami dari awal! Akses buat masa ini melalui jemputan; menyertai senarai menunggu tidak memulakan langganan.',
    groupTitle: 'Terima kasih kerana menyokong Jentera dari awal.',
    groupIntro: 'Anda membantu kami membina produk yang hebat. Kami mahu bekerjasama dan mendengar maklum balas anda. Sertai Kumpulan WhatsApp Pengasas untuk akses terus kepada pengasas—kongsi idea, laporkan masalah, atau dapatkan bantuan aliran kerja pertama. Penyertaan adalah pilihan.',
    groupPrivacy: 'Ahli lain mungkin nampak profil WhatsApp dan maklumat yang anda kongsi. Jangan kongsi kata laluan, data peribadi pelanggan atau fail sulit.',
    groupJoin: 'Sertai Kumpulan WhatsApp Pengasas',
    workflowTitle: 'Apa yang anda mahu Staf AI bantu dahulu?',
    workflowIntro: 'Mulakan dengan satu kerja berulang. Seterusnya, kita kenali bisnes anda dan sediakan tugasan pertama untuk semakan.',
    workflowCategories: { sales: 'Jualan & susulan', admin: 'Pentadbiran & kemasukan data', reports: 'Laporan', research: 'Penyelidikan & pemantauan', marketing: 'Pemasaran', other: 'Kerja lain' },
    workflowExamples: { sales: 'Sediakan sebut harga atau draf susulan', admin: 'Kemas kini hamparan atau sediakan dokumen', reports: 'Tukar angka mingguan kepada laporan berguna', research: 'Banding pembekal atau pantau maklumat awam', marketing: 'Sediakan pelan kandungan atau draf kempen', other: 'Terangkan kerja yang anda mahu bantuan' },
    repeatedTask: 'Apakah satu kerja yang anda ulang setiap hari atau setiap minggu?',
    repeatedPlaceholder: 'Setiap Jumaat, saya tukar hamparan jualan kepada laporan mingguan…',
    workflowNext: 'Pilih sebagai aliran kerja pertama',
    workflowMissing: 'Pilih kategori dan terangkan satu kerja berulang dahulu.',
    workflowPrivacy: 'Jangan masukkan kata laluan atau butiran peribadi pelanggan. Pilihan ini tidak menjalankan atau menjadualkan kerja.',
    changeWorkflow: 'Tukar aliran kerja pertama',
    workflowCategoryField: 'Kategori aliran kerja pertama', workflowTaskField: 'Kerja berulang anda',
    workflowChoice: 'Aliran kerja pilihan anda', workflowOutcome: 'Hasil pertama dan pelan berulang untuk semakan',
    workflowPrompt: 'Bantu saya sediakan aliran kerja berulang pertama untuk tugasan ini:',
    workflowInstructions: 'Sediakan hasil pertama yang boleh disunting jika sesuai, senarai semak berulang, input yang diperlukan, dan langkah yang memerlukan kelulusan saya atau sambungan yang disokong. Jangan dakwa aliran kerja ini sudah aktif atau dijadualkan.',
    computerMoment: 'Kenali Staf AI anda.',
    readyChecks: ['Komputer sedia', 'Pelayar sedia', 'Ruang kerja sedia', 'Jentera sedia'],
    readyChecksNote: 'Persediaan disahkan pada versi sasaran anda. Komputer yang melahu mungkin perlu diaktifkan apabila tugasan dimulakan.',
    learning: 'Mengenali bisnes anda', readyToReview: 'Gambaran bisnes anda mula terbentuk.',
    selectedDetails: 'butiran dipilih', previewNote: 'Berdasarkan butiran yang dipilih di bawah. Belum ada yang disahkan.',
    sourceWaiting: 'Menunggu', sourceReading: 'Membaca', sourceRead: 'Dibaca', sourceFailed: 'Tidak dapat dibaca',
    draftReady: 'Draf pertama anda sudah tersedia.', responseReady: 'Ini jawapan Jentera.', contentOutcome: '3 hantaran boleh sunting dan pelan seminggu',
    replyOutcome: 'Balasan boleh guna semula dan disesuaikan', checklistOutcome: 'Senarai semak langkah demi langkah',
    workshopOutcome: 'Mesej susulan untuk semakan anda',
    steps: ['Kenalkan bisnes anda', 'Semak yang saya temui', 'Tugasan pertama anda'],
    title: 'Di mana saya boleh belajar tentang bisnes anda?',
    intro: 'Beri satu halaman, dokumen, atau beberapa ayat. Saya akan susun butiran bisnes untuk anda semak.',
    website: 'Laman web atau halaman awam', social: 'Halaman awam lain (pilihan)', upload: 'Muat naik dokumen', describe: 'Terangkan bisnes anda',
    limit: 'Membaca halaman yang diberi, bukan seluruh laman web. Untuk halaman yang perlu log masuk atau banyak JavaScript, muat naik dokumen atau terangkan bisnes anda.',
    fileNote: 'PDF, Word, imej, teks, Markdown atau CSV. Hingga 8 MB (fail teks: 1 MB). Hanya fakta yang diekstrak disimpan.',
    name: 'Nama bisnes', about: 'Apa yang anda tawarkan, dan siapa pelanggan anda?',
    fields: { 'business.name': 'Nama bisnes', 'business.about': 'Tentang bisnes anda', 'business.address': 'Alamat', 'business.phone': 'Telefon', 'business.email': 'E-mel' } as Record<string, string>,
    read: 'Kenali bisnes saya', reading: 'Sedang membaca sumber anda…', review: 'Ini yang saya faham.',
    reviewNote: 'Ini cadangan butiran, bukan dakwaan yang disahkan. Betulkan yang salah dan pilih hanya yang Jentera patut gunakan.',
    source: 'Sumber', manual: 'Anda', empty: 'Saya belum menemui butiran bisnes yang cukup jelas. Cuba halaman lain, muat naik dokumen, atau terangkan bisnes anda. Belum ada yang disahkan.',
    failed: 'Sumber itu tidak dapat dibaca. Cuba sumber lain atau masukkan butiran sendiri.',
    back: 'Tukar sumber', confirm: 'Sahkan butiran & sediakan Jentera', saving: 'Menyimpan butiran anda…',
    consent: 'Pengesahan menyimpan butiran pilihan anda dan mula menyediakan komputer bisnes. Anda akan pilih tugasan selepas ini; tiada apa dihantar atau diterbitkan.',
    retry: 'Cuba lagi', keep: 'Gunakan butiran ini', missing: 'Tambah sumber, dokumen, atau penerangan bisnes dahulu.',
    resume: 'Input terdahulu anda ada di sini. Baca sumber sekarang untuk membina pengetahuan bisnes sebenar.',
    jobs: 'Beri Staf AI anda tugasan pertamanya.',
    jobsNote: 'Pilih permulaan, sunting arahan, dan minta Jentera hasilkan draf. Tiada apa dihantar atau diterbitkan.',
    draft: 'Arahan anda', start: 'Hasilkan draf ini', starting: 'Memulakan tugasan…', open: 'Lihat hasil kerja',
    waiting: 'Sediakan dan simpan tugasan pertama sementara komputer disediakan. Tiada kerja dijalankan sehingga anda memilih untuk memulakannya.',
    saveBrief: 'Simpan tugasan pertama', savingBrief: 'Menyimpan tugasan pertama…', savedButton: 'Tugasan pertama disimpan',
    savedWaiting: 'Arahan anda sudah disimpan. Anda boleh keluar dan kembali apabila komputer sedia.',
    savedReady: 'Arahan disimpan dan komputer sudah sedia. Pilih “Hasilkan draf ini” untuk bermula.',
    saveFailed: 'Tugasan pertama tidak dapat disimpan. Sila cuba lagi.',
    content: 'Kandungan seminggu', reply: 'Balasan pertanyaan', checklist: 'Senarai semak praktikal', workshop: 'Susulan bengkel',
    safety: 'Gunakan butiran bisnes saya yang disahkan. Jangan reka harga, pelanggan, hasil atau polisi. Tandakan maklumat yang belum ada. Hasilkan dokumen Markdown yang boleh disunting. Draf sahaja: jangan hantar, terbitkan, jadualkan atau hubungi sesiapa.',
    contentPrompt: 'Sediakan pelan kandungan seminggu untuk bisnes saya, dengan tiga draf hantaran, sasaran pembaca dan seruan tindakan yang jelas.',
    replyPrompt: 'Drafkan balasan pertama yang boleh digunakan semula untuk bakal pelanggan yang bertanya tentang perkhidmatan kami, dengan ruang bagi butiran khusus pertanyaan mereka.',
    checklistPrompt: 'Sediakan senarai semak praktikal untuk menyampaikan perkhidmatan atau produk utama kami, daripada pertanyaan awal hingga susulan.',
    workshopPrompt: 'Drafkan mesej susulan untuk peserta bengkel, dengan ruang untuk nama bengkel, bahan dan pautan maklum balas.',
  },
};
