export const onboardingCopy = {
  en: {
    steps: ['Introduce your business', 'Review what I found', 'Your first useful job'],
    title: 'Where can I learn about your business?',
    intro: 'Give me a page, a document, or a few sentences. I’ll turn it into business details you can check.',
    website: 'Website or public page', social: 'Another public page (optional)', upload: 'Upload a document', describe: 'Describe your business',
    limit: 'Reads the page you provide, not the whole website. For login-only or JavaScript-heavy pages, upload a document or describe your business.',
    fileNote: 'PDF, Word, images, text, Markdown or CSV. Up to 8 MB (text files: 1 MB). Only extracted facts are kept.',
    name: 'Business name', about: 'What do you offer, and who do you help?',
    fields: { 'business.name': 'Business name', 'business.about': 'About your business', 'business.address': 'Address', 'business.phone': 'Phone', 'business.email': 'Email' } as Record<string, string>,
    read: 'Learn about my business', reading: 'Reading your source…', review: 'Here’s what I understood.',
    reviewNote: 'These are proposed details, not verified claims. Edit what’s wrong and select only what you want Jentera to use.',
    source: 'Source', manual: 'You', empty: 'I couldn’t find enough clear business details. Try another page, upload a document, or describe the business. Nothing has been confirmed.',
    failed: 'That source could not be read. Try another source or add the details yourself.',
    back: 'Change source', confirm: 'Confirm details & prepare Jentera', saving: 'Saving your details…',
    consent: 'Confirming saves your selected details and starts preparing your business computer. You’ll choose a job next; nothing is sent or published.',
    retry: 'Try again', keep: 'Use this detail', missing: 'Add a source, document, or business description first.',
    resume: 'Your earlier inputs are here. Read the source now to build your real business knowledge.',
    jobs: 'What should I take off your plate first?',
    jobsNote: 'Choose a starting point, edit the brief, and ask Jentera to produce a draft. Nothing is sent or published.',
    draft: 'Your brief', start: 'Create this draft', starting: 'Starting your job…', open: 'View your work',
    waiting: 'Your computer is getting ready. You can choose and edit your first job while you wait.',
    content: 'A week of content', reply: 'An enquiry reply', checklist: 'A practical checklist',
    workshop: 'A workshop follow-up',
    safety: 'Use my confirmed business details. Do not invent prices, customers, results or policies. Mark missing information clearly. Create an editable Markdown document. Draft only: do not send, publish, schedule or contact anyone.',
    contentPrompt: 'Create a practical one-week content plan for my business, with three draft posts, intended audiences and clear calls to action.',
    replyPrompt: 'Draft a reusable first reply for a prospective customer asking about our services, with placeholders for details that depend on their enquiry.',
    checklistPrompt: 'Create a practical checklist for delivering our main service or product, from the initial enquiry to follow-up.',
    workshopPrompt: 'Draft a follow-up message for workshop participants, with placeholders for the workshop name, resources and feedback link.',
  },
  bm: {
    steps: ['Kenalkan bisnes anda', 'Semak yang saya temui', 'Tugasan pertama anda'],
    title: 'Di mana saya boleh belajar tentang bisnes anda?',
    intro: 'Beri satu halaman, dokumen, atau beberapa ayat. Saya akan susun butiran bisnes untuk anda semak.',
    website: 'Laman web atau halaman awam', social: 'Halaman awam lain (pilihan)', upload: 'Muat naik dokumen', describe: 'Terangkan bisnes anda',
    limit: 'Membaca halaman yang diberi, bukan seluruh laman web. Untuk halaman yang perlu log masuk atau banyak JavaScript, muat naik dokumen atau terangkan bisnes anda.',
    fileNote: 'PDF, Word, imej, teks, Markdown atau CSV. Hingga 8 MB (fail teks: 1 MB). Hanya fakta yang diekstrak disimpan.',
    name: 'Nama bisnes', about: 'Apa yang anda tawarkan, dan siapa pelanggan anda?',
    fields: { 'business.name': 'Nama bisnes', 'business.about': 'Tentang bisnes anda', 'business.address': 'Alamat', 'business.phone': 'Telefon', 'business.email': 'E-mel' } as Record<string, string>,
    read: 'Kenali bisnes saya', reading: 'Sedang membaca sumber anda…', review: 'Ini yang saya faham.',
    reviewNote: 'Ini cadangan butiran, bukan dakwaan yang disahkan. Betulkan yang salah dan pilih hanya yang Jentera patut gunakan.',
    source: 'Sumber', manual: 'Anda', empty: 'Saya belum menemui butiran bisnes yang cukup jelas. Cuba halaman lain, muat naik dokumen, atau terangkan bisnes anda. Belum ada yang disahkan.',
    failed: 'Sumber itu tidak dapat dibaca. Cuba sumber lain atau masukkan butiran sendiri.',
    back: 'Tukar sumber', confirm: 'Sahkan butiran & sediakan Jentera', saving: 'Menyimpan butiran anda…',
    consent: 'Pengesahan menyimpan butiran pilihan anda dan mula menyediakan komputer bisnes. Anda akan pilih tugasan selepas ini; tiada apa dihantar atau diterbitkan.',
    retry: 'Cuba lagi', keep: 'Gunakan butiran ini', missing: 'Tambah sumber, dokumen, atau penerangan bisnes dahulu.',
    resume: 'Input terdahulu anda ada di sini. Baca sumber sekarang untuk membina pengetahuan bisnes sebenar.',
    jobs: 'Kerja apa yang patut saya bantu dahulu?',
    jobsNote: 'Pilih permulaan, sunting arahan, dan minta Jentera hasilkan draf. Tiada apa dihantar atau diterbitkan.',
    draft: 'Arahan anda', start: 'Hasilkan draf ini', starting: 'Memulakan tugasan…', open: 'Lihat hasil kerja',
    waiting: 'Komputer anda sedang disediakan. Anda boleh memilih dan menyunting tugasan pertama sementara menunggu.',
    content: 'Kandungan seminggu', reply: 'Balasan pertanyaan', checklist: 'Senarai semak praktikal', workshop: 'Susulan bengkel',
    safety: 'Gunakan butiran bisnes saya yang disahkan. Jangan reka harga, pelanggan, hasil atau polisi. Tandakan maklumat yang belum ada. Hasilkan dokumen Markdown yang boleh disunting. Draf sahaja: jangan hantar, terbitkan, jadualkan atau hubungi sesiapa.',
    contentPrompt: 'Sediakan pelan kandungan seminggu untuk bisnes saya, dengan tiga draf hantaran, sasaran pembaca dan seruan tindakan yang jelas.',
    replyPrompt: 'Drafkan balasan pertama yang boleh digunakan semula untuk bakal pelanggan yang bertanya tentang perkhidmatan kami, dengan ruang bagi butiran khusus pertanyaan mereka.',
    checklistPrompt: 'Sediakan senarai semak praktikal untuk menyampaikan perkhidmatan atau produk utama kami, daripada pertanyaan awal hingga susulan.',
    workshopPrompt: 'Drafkan mesej susulan untuk peserta bengkel, dengan ruang untuk nama bengkel, bahan dan pautan maklum balas.',
  },
};
